export const IMAGES = {
  BANNER: "/assets/images/banner.jpg",
  VILLA_OCEAN: "/assets/images/villaocean.jpg",
  MOUNTAIN_ESCAPE: "/assets/images/mountainescape.jpg",
  COZY_DESERT: "/assets/images/cozydesert.jpg",
  CITY_LIGHTS: "/assets/images/citylights.jpg",
  RIVERSIDE: "/assets/images/riverside.jpg",
  MODERN_BEACH: "/assets/images/modernbeach.jpg",
  LAKESIDE: "/assets/images/lakeside.jpg",
  TROPICAL_GARDEN: "/assets/images/tropicalgarden.jpg",
  URBAN_LOFT: "/assets/images/urbanloft.jpg",
  SECLUDED_FOREST: "/assets/images/secludedforest.jpg",
  CLIFFSIDE: "/assets/images/cliffside.jpg",
  COASTAL_ESCAPE: "/assets/images/coastalescape.jpg",
  HISTORICAL: "/assets/images/historical.jpg",
  DOWNTOWN: "/assets/images/downtown.jpg",
  LUXURY_SAFARI: "/assets/images/luxurysafari.jpg",
  COUNTRYSIDE: "/assets/images/countryside.jpg",
  RIVERFRONT: "/assets/images/riverfront.jpg",
  SKI_CHALET: "/assets/images/skichalet.jpg",
  ISLAND_PARADISE: "/assets/images/islandparadise.jpg",
  CLIFFTOP: "/assets/images/clifftop.jpg",
};
