import { Listing, PropertyProps } from "@/interfaces";
import { IMAGES } from "./images";

// Homepage / marketing listings
export const listings: Listing[] = [
  {
    id: 1,
    title: "Modern Apartment",
    description: "A stylish apartment in the city center.",
    image: IMAGES.BANNER,
  },
];

// Property sample data
export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    id: "101",
    name: "Villa Ocean Breeze",
    description: "Luxurious villa with ocean view and private pool.",
    address: { state: "Seminyak", city: "Bali", country: "Indonesia" },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    offers: { bed: "3", shower: "3", occupants: "4-6" },
    image: IMAGES.VILLA_OCEAN,
    discount: "",
  },
  {
    id: "102",
    name: "Mountain Escape Chalet",
    description: "Cozy chalet with mountain view and fireplace.",
    address: { state: "Aspen", city: "Colorado", country: "USA" },
    rating: 4.70,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: IMAGES.MOUNTAIN_ESCAPE,
    discount: "30",
  },
  {
    id: "103",
    name: "Cozy Desert Retreat",
    description: "Peaceful retreat in the desert, perfect for couples.",
    address: { state: "Palm Springs", city: "California", country: "USA" },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: IMAGES.COZY_DESERT,
    discount: "",
  },
  {
    id: "104",
    name: "City Lights Penthouse",
    description: "Modern penthouse with stunning city views.",
    address: { state: "New York", city: "New York", country: "USA" },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    offers: { bed: "2", shower: "2", occupants: "2-4" },
    image: IMAGES.CITY_LIGHTS,
    discount: "15",
  },
  {
    id: "105",
    name: "Riverside Cabin",
    description: "Cabin by the river with private dock and kayaks.",
    address: { state: "Queenstown", city: "Otago", country: "New Zealand" },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    offers: { bed: "3", shower: "2", occupants: "4-6" },
    image: IMAGES.RIVERSIDE,
    discount: "20",
  },
  {
    id: "106",
    name: "Modern Beachfront Villa",
    description: "Beachfront villa with private pool and chef service.",
    address: { state: "Sidemen", city: "Bali", country: "Indonesia" },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    offers: { bed: "5", shower: "4", occupants: "8-10" },
    image: IMAGES.MODERN_BEACH,
    discount: "",
  },
  {
    id: "107",
    name: "Lakeside Chalet",
    description: "Chalet by the lake with mountain views.",
    address: { state: "Banff", city: "Alberta", country: "Canada" },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: IMAGES.LAKESIDE,
    discount: "10",
  },
  {
    id: "108",
    name: "Tropical Garden Villa",
    description: "Villa surrounded by tropical gardens.",
    address: { state: "Koh Samui", city: "Surat Thani", country: "Thailand" },
    rating: 4.80,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    offers: { bed: "3", shower: "3", occupants: "5-6" },
    image: IMAGES.TROPICAL_GARDEN,
    discount: "25",
  },
];